kind: PersistentVolume
apiVersion: v1
metadata:
  name: antoniocamas-1g-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/antoniocamas"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: antoniocamas-pvc-1g
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
