kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.prefix }}1g-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolumePath | quote }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.prefix }}pvc-1g
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
