apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - host: {{ .Values.webDomain }}
    http:
      paths:
      - path: {{ .Values.uriPath }}
        backend:
          serviceName: java-webapp
          servicePort: {{ .Values.javawebappContainerPort }}
