---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}java-webapp-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.prefix }}java-webapp
  replicas: {{ .Values.replicaCount }} 
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: {{ .Values.prefix }}java-webapp
    spec:
      containers:
      - name: {{ .Values.prefix }}java-webapp
        image: codeurjc/java-webapp-bbdd:v2
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysqlRootPass }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysqlDatabase }}
        ports:
        - containerPort: {{ .Values.javawebappContainerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}java-webapp
  labels:
    app: {{ .Values.prefix }}java-webapp
spec:
  ports:
    - port: {{ .Values.javawebappContainerPort }}
      targetPort: {{ .Values.javawebappContainerPort }}
      protocol: TCP
      name: {{ .Values.prefix }}java-webapp-port
  selector:
    app: {{ .Values.prefix }}java-webapp
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}db-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.prefix }}db
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: {{ .Values.prefix }}db
    spec:
      containers:
      - name: {{ .Values.prefix }}db
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysqlRootPass }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysqlDatabase }}
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: {{ .Values.prefix }}db-storage
      volumes:
      - name: {{ .Values.prefix }}db-storage
        persistentVolumeClaim:
          claimName: {{ .Values.prefix }}pvc-1g
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: {{ .Values.prefix }}db
spec:
  ports:
    - port: 3306
      protocol: TCP
      name: {{ .Values.prefix }}bbdd-port
  selector:
    app: {{ .Values.prefix }}db
  type: ClusterIP
